-- MyDent Complete Production Database Sync Dump
-- Generated from SQLite source of truth for Hostinger MySQL import
SET FOREIGN_KEY_CHECKS=0;

-- Data for table `products` (4 rows)
INSERT INTO `products` (`id`, `name`, `description`, `category`, `price`, `discount_price`, `quantity`, `thumbnail`, `category_thumbnail`, `images`, `created_at`, `updated_at`) VALUES (1, 'MyDent Clear Aligner Starter Kit', 'Complete home alignment starter kit including 3D scan voucher, impression kit, and personal alignment plan.', 'Aligners', 24999, 19999, 50, 'assets/image/infycare-logo.png', NULL, NULL, '2026-08-17 19:20:02', '2026-08-17 19:20:02') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `products` (`id`, `name`, `description`, `category`, `price`, `discount_price`, `quantity`, `thumbnail`, `category_thumbnail`, `images`, `created_at`, `updated_at`) VALUES (2, 'MyDent Aligner Cleaning Crystals (30 Pack)', 'Specially formulated effervescent cleaning tablets to keep clear aligners fresh, transparent, and odor-free.', 'Accessories', 1199, 899, 100, 'assets/image/infycare-logo.png', NULL, NULL, '2026-08-17 19:20:02', '2026-08-17 19:20:02') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `products` (`id`, `name`, `description`, `category`, `price`, `discount_price`, `quantity`, `thumbnail`, `category_thumbnail`, `images`, `created_at`, `updated_at`) VALUES (3, 'MyDent Aligner Removal Tool & Travel Case', 'Ergonomic aligner extraction tool with protective magnetic travel storage case.', 'Accessories', 699, 499, 150, 'assets/image/infycare-logo.png', NULL, NULL, '2026-08-17 19:20:02', '2026-08-17 19:20:02') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `products` (`id`, `name`, `description`, `category`, `price`, `discount_price`, `quantity`, `thumbnail`, `category_thumbnail`, `images`, `created_at`, `updated_at`) VALUES (4, 'MyDent Ultrasonic UV Aligner Sanitizer', 'Advanced 42kHz ultrasonic cleaner with UV-C sterilization for deep aligner cleaning in 5 minutes.', 'Care', 3499, 2499, 40, 'assets/image/infycare-logo.png', NULL, NULL, '2026-08-17 19:20:02', '2026-08-17 19:20:02') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `orders` (14 rows)
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (1, 'njnkvkd', '9873319008', 'f@gmail.com', 'fndsfmndf', 'dfdf', 'fffaf', 'dfdsfds', '12343', 'COD', '', 0, 0, 10.5, '2025-04-29 07:29:38', '2025-04-29 07:29:38', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (2, 'dkjfssl', '9873319008', 'g@gmail.com', 'kdfdsf', 'kfmskmf', 'eowo', 'slaakla', '45678', 'COD', '"[\\"Ram\\"]"', 0, 0, 1.05, '2025-04-29 07:40:51', '2025-04-30 01:15:33', 'Processing') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (3, 'lfkdlskfsd', '9876567833', 'jh@gmail.com', 'kdfndnfd', 'dfkdkfndf', 'erewrwe', 'dkfkdsf', '8765', 'COD', '"[\\"Ram\\",\\"Aligner Cleaning Foam\\"]"', 0, 0, 100.8, '2025-04-29 07:42:01', '2025-04-30 01:12:09', 'Delivered') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (4, 'Lucky Mishra', '6393359561', 'mishra2000lucky@gmail.com', '616/059 A\\nMadiyaon', 'India', 'Uttar Pradesh', 'Lucknow', '226021', 'COD', '"[\\"Aligner Cleaning Foam\\"]"', 0, 0, 99.75, '2025-04-30 01:34:08', '2025-04-30 01:34:08', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (5, 'Lucky Mishra', '6393359561', 'mishra2000lucky@gmail.com', 'hjvjvhvjhv', 'India', 'Uttar Pradesh', 'Lucknow', '226021', 'COD', '"[\\"chewe\\",\\"advanced water flosser\\"]"', 0, 0, 110.25, '2025-06-30 09:43:35', '2025-06-30 09:43:35', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (6, 'Lucky Mishra', '6393359561', 'mishra2000lucky@gmail.com', 'iwjeoiwj', 'India', 'Uttar Pradesh', 'Lucknow', '226021', 'COD', '"[\\"Ram\\"]"', 0, 0, 3.15, '2025-06-30 10:11:05', '2025-06-30 10:11:05', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (7, 'Lucky Mishra', '6393359561', 'mishra2000lucky@gmail.com', 'nbcmxmcx', 'India', 'Uttar Pradesh', 'Lucknow', '226021', 'COD', '"[\\"Tooth alligner\\"]"', 0, 0, 10.5, '2025-06-30 10:24:56', '2025-06-30 10:24:56', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (8, 'Lucky Mishra', '6393359562', 'mishra2000lucky@gmail.com', 'bcmbcm', 'India', 'Uttar Pradesh', 'Lucknow', '226022', 'COD', '"[\\"Ram\\"]"', 0, 0, 1.05, '2025-06-30 22:40:05', '2025-06-30 22:40:05', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (9, 'Lucky Mishra', '0639335956', 'mishra2000luckyy@gmail.com', 'mnbnbm', 'India', 'Uttar Pradesh', 'Lucknow', '226021', 'Online', '"[\\"chewe\\"]"', 0, 0, 105, '2025-06-30 23:12:11', '2025-06-30 23:12:11', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (10, 'Lucky Mishra', '0639335956', 'mishra2000lucky@gmail.com', '616/059 A\\r\\nMadiyaon', 'India', 'Uttar Pradesh', 'Lucknow', '226021', 'COD', '"[\\"chewe\\"]"', 0, 0, 105, '2025-06-30 23:47:54', '2025-06-30 23:47:54', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (11, 'Lucky Mishra', '0639335956', 'mishra2000lucky@gmail.com', 'nabmnbz', 'India', 'Uttar Pradesh', 'Lucknow', '226021', 'Online', '"[\\"Ram\\"]"', 0, 0, 2.1, '2025-07-01 01:53:05', '2025-07-05 08:31:18', 'Processing') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (12, 'Cleaners', '9876543212', 'mydent@gmail.com', 'bhjjh', 'India', 'uy', 'nbhb', '765432', 'COD', '"[\\"pull tool\\"]"', 0, 0, 105, '2025-07-25 15:53:09', '2025-07-25 15:53:09', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (13, 'Cleaners', '9876543212', 'support@mydent.in', 'nbmn', 'India', 'uy', 'bnmb', '765432', 'Online', '"[\\"Aligner Cleaning Foam\\"]"', 0, 0, 99.75, '2025-07-25 15:55:23', '2025-07-25 15:55:23', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `orders` (`id`, `name`, `phone`, `email`, `address`, `country`, `state`, `city`, `pincode`, `payment_method`, `products`, `subtotal`, `tax`, `total`, `created_at`, `updated_at`, `status`) VALUES (14, 'test 4', '9849492909', 'shaikfarhat79@gmail.com', 'aaa', 'India', 'aaa', 'aaa', '22222', 'Online', '"[\\"test 4\\"]"', 0, 0, 9.45, '2025-07-25 16:06:33', '2025-07-25 16:06:33', 'Pending') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `categories` (1 rows)
INSERT INTO `categories` (`id`, `name`, `is_active`, `created_at`, `updated_at`) VALUES (1, 'alligners', 1, '2025-04-28 01:40:32', '2025-04-28 01:40:32') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `service_categories` (7 rows)
INSERT INTO `service_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (1, 'Dentist', '2023-09-28 07:51:55', '2023-09-28 07:51:55') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (2, 'Dieticians', '2023-09-28 07:51:55', '2023-09-28 07:51:55') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (3, 'General Physicians', '2023-09-28 07:51:55', '2023-09-28 07:51:55') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (4, 'Gynecologists', '2023-09-28 07:51:55', '2023-09-28 07:51:55') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (5, 'physiotherapy', '2023-09-28 07:51:55', '2023-09-28 07:51:55') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (6, 'Psychologist', '2023-09-28 07:51:55', '2023-09-28 07:51:55') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_categories` (`id`, `name`, `created_at`, `updated_at`) VALUES (7, 'Orthodontist', '2025-05-14 07:00:59', '2025-05-14 07:00:59') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `specializations` (4 rows)
INSERT INTO `specializations` (`id`, `name`, `created_at`, `updated_at`) VALUES (7, 'Pathology', '2023-09-28 07:51:48', '2023-09-28 07:51:48') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `specializations` (`id`, `name`, `created_at`, `updated_at`) VALUES (10, 'Physiology', '2023-09-28 07:51:48', '2023-09-28 07:51:48') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `specializations` (`id`, `name`, `created_at`, `updated_at`) VALUES (11, 'Physical Medicine', '2023-09-28 07:51:48', '2023-09-28 07:51:48') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `specializations` (`id`, `name`, `created_at`, `updated_at`) VALUES (13, 'orthodontics', '2025-07-05 08:41:24', '2025-07-05 08:41:24') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `services` (6 rows)
INSERT INTO `services` (`id`, `category_id`, `name`, `charges`, `status`, `created_at`, `updated_at`, `short_description`) VALUES (1, 7, 'Teeth whitening', 1200.0, 1, '2023-09-28 07:51:55', '2025-07-08 18:51:12', 'Teeth whitening is a cosmetic procedure that lightens stains') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `services` (`id`, `category_id`, `name`, `charges`, `status`, `created_at`, `updated_at`, `short_description`) VALUES (2, 7, 'Aligners', 50000.0, 1, '2023-09-28 07:51:55', '2025-07-08 18:57:11', 'clear aligners') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `services` (`id`, `category_id`, `name`, `charges`, `status`, `created_at`, `updated_at`, `short_description`) VALUES (3, 7, 'Oral category', 500.0, 1, '2023-09-28 07:51:55', '2025-07-08 18:59:31', 'All item related to aligners') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `services` (`id`, `category_id`, `name`, `charges`, `status`, `created_at`, `updated_at`, `short_description`) VALUES (4, 7, 'Intraoral scanning', 1000.0, 1, '2023-09-28 07:51:55', '2025-07-08 19:04:43', '3D scanning of teeth') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `services` (`id`, `category_id`, `name`, `charges`, `status`, `created_at`, `updated_at`, `short_description`) VALUES (7, 7, 'Orthodontist Consultation', 200.0, 1, '2025-07-05 08:39:24', '2025-07-08 19:01:04', 'To rule out the problem and solution') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `services` (`id`, `category_id`, `name`, `charges`, `status`, `created_at`, `updated_at`, `short_description`) VALUES (8, 1, 'Cleaners', 500.0, 0, '2025-07-14 19:39:35', '2025-07-18 08:46:41', 'ndfjkfnkfnsfs') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `doctors` (6 rows)
INSERT INTO `doctors` (`id`, `user_id`, `experience`, `created_at`, `updated_at`, `twitter_url`, `linkedin_url`, `instagram_url`) VALUES (1, 2, NULL, '2026-08-17 15:50:11', '2026-08-17 15:50:11', NULL, NULL, NULL) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctors` (`id`, `user_id`, `experience`, `created_at`, `updated_at`, `twitter_url`, `linkedin_url`, `instagram_url`) VALUES (11, 14, 5.0, NULL, NULL, NULL, '2025-04-28 01:08:09', '2025-04-28 01:08:09') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctors` (`id`, `user_id`, `experience`, `created_at`, `updated_at`, `twitter_url`, `linkedin_url`, `instagram_url`) VALUES (12, 20, 66.0, NULL, NULL, NULL, '2025-05-08 18:01:58', '2025-05-08 18:01:58') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctors` (`id`, `user_id`, `experience`, `created_at`, `updated_at`, `twitter_url`, `linkedin_url`, `instagram_url`) VALUES (14, 28, 5.0, NULL, NULL, NULL, '2025-07-08 18:54:21', '2025-07-08 18:54:21') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctors` (`id`, `user_id`, `experience`, `created_at`, `updated_at`, `twitter_url`, `linkedin_url`, `instagram_url`) VALUES (15, 32, NULL, NULL, NULL, NULL, '2025-07-15 10:37:41', '2025-07-15 10:37:41') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctors` (`id`, `user_id`, `experience`, `created_at`, `updated_at`, `twitter_url`, `linkedin_url`, `instagram_url`) VALUES (16, 33, 5.0, NULL, NULL, NULL, '2025-07-15 16:31:02', '2025-07-15 16:31:02') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `patients` (19 rows)
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (1, 'UNIQUE12', 3, '2023-09-28 07:51:48', '2023-09-28 07:51:48') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (2, 'VYDVEANW', 4, '2026-08-17 18:33:51', '2026-08-17 18:33:51') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (6, 'HCTGQYR7', 19, '2025-04-28 01:22:50', '2025-04-28 01:22:50') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (7, '7AST5ZWO', 21, '2025-05-09 17:25:56', '2025-05-09 17:25:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (8, 'WTY9OI90', 22, '2025-06-10 07:18:01', '2025-06-10 07:18:01') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (9, 'CGSKNGBY', 23, '2025-06-14 18:31:41', '2025-06-14 18:31:41') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (10, 'DWJHCKDB', 25, '2025-07-05 09:15:42', '2025-07-05 09:15:42') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (11, 'ZS2RRKBX', 26, '2025-07-05 09:16:10', '2025-07-05 09:16:10') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (12, 'PX6MR1B4', 27, '2025-07-05 09:17:23', '2025-07-05 09:17:23') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (13, '5GOWBZQ4', 29, '2025-07-13 14:54:53', '2025-07-13 14:54:53') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (14, 'KDKNMEKU', 30, '2025-07-14 19:40:23', '2025-07-14 19:40:23') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (15, 'KA7J8RAO', 31, '2025-07-14 19:46:35', '2025-07-14 19:46:35') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (16, '1GEWUEFT', 35, '2025-07-16 20:09:48', '2025-07-16 20:09:48') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (17, 'TS0PZTMF', 36, '2025-09-23 16:05:31', '2025-09-23 16:05:31') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (18, 'XW8AN00C', 37, '2025-10-18 06:55:27', '2025-10-18 06:55:27') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (19, 'IV6VF03S', 38, '2025-10-26 00:08:09', '2025-10-26 00:08:09') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (20, 'GV9UPKUA', 39, '2025-11-11 17:34:22', '2025-11-11 17:34:22') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (21, 'PFK9HTIO', 40, '2026-01-10 16:55:17', '2026-01-10 16:55:17') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `patients` (`id`, `patient_unique_id`, `user_id`, `created_at`, `updated_at`) VALUES (22, 'LMVLPMN5', 41, '2026-02-07 09:33:22', '2026-02-07 09:33:22') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `blogs` (18 rows)
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (1, 'Understanding Clear Aligner Treatment: What to Expect', 'assets/image/infycare-logo.png', 'Crowded Teeth & Overbite', 'Moderate', '6 Months', 18, 'Clear aligners have revolutionized modern orthodontics. Unlike traditional metal braces, custom 3D printed aligners are virtually invisible, comfortable to wear, and removable for dining and oral hygiene.', '2026-08-17 19:21:08', '2026-08-17 19:21:08') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (12, 'Rayapati story', 'assets/image/infycare-logo.png', 'spacing', 'Simple', '8 months', 30, '"I had small gaps between my teeth that always bothered me. I chose Mydent Aligners, and I couldn’t be happier! In just 8 months, my smile completely changed. The aligners were clear, comfortable, and fit perfectly into my daily routine. The support from the Mydent team was excellent throughout the journey. I now smile with pride, thanks to Mydent!"\\r\\n\\r\\n⭐️⭐️⭐️⭐️⭐️', '2025-07-08 09:47:44', '2025-08-01 09:15:25') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (13, 'teja story', 'assets/image/infycare-logo.png', 'spacing', 'Moderate', '14', 52, '“I always felt conscious about the gaps in my teeth. I didn’t want metal braces, so I chose Mydent Aligners – and it was the best decision.\\r\\n\\r\\nOver 14 months and 52 aligners, my smile changed completely. The aligners were comfortable, easy to wear, and almost invisible.\\r\\n\\r\\nThe team supported me throughout the journey, and I could see visible changes every month. Now, I feel so much more confident when I smile.\\r\\n\\r\\nThank you, Mydent, for giving me the smile I always wanted!”\\r\\n\\r\\n— Teja R., Mydent Patient', '2025-07-08 10:01:28', '2025-08-01 09:15:14') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (14, 'kaif story', 'assets/image/infycare-logo.png', 'crowding', 'Severe', '14', 42, '“My teeth were crowded and uneven, and it always made me hesitate to smile in photos. I wanted a solution that was discreet and effective – that’s when I found Mydent Aligners.\\r\\n\\r\\nWith just 42 aligners, my teeth started shifting into place beautifully. The aligners were comfortable, easy to remove, and nobody even noticed I was wearing them.\\r\\n\\r\\nThe process was smooth, and the results were amazing. My smile looks aligned and clean now – and I feel more confident every day.\\r\\n\\r\\nMydent made the journey simple and stress-free. Highly recommended!”\\r\\n\\r\\n— Kaif M', '2025-07-08 10:04:27', '2025-08-01 09:15:04') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (15, 'yunus story', 'assets/image/infycare-logo.png', 'underbite', 'Severe', '18 months', 48, '“I had a severe underbite that made it hard for me to chew properly and affected my confidence. I always thought I’d need surgery or braces, but then I discovered Mydent Aligners.\\r\\n\\r\\nFrom the start, the team explained everything clearly and planned a treatment just for me. It wasn’t easy, but the aligners worked better than I imagined.\\r\\n\\r\\nMy bite slowly improved, and now my teeth are aligned properly. No brackets, no wires – just a smooth, step-by-step transformation.\\r\\n\\r\\nI’m really thankful to Mydent for handling a tough case like mine with such care and expertise.”\\r\\n\\r\\n— Yunus A., Mydent Patient', '2025-07-08 10:07:30', '2025-08-01 09:14:48') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (16, 'sowjanya story', 'assets/image/infycare-logo.png', 'open bite', 'Severe', '28 months', 64, '“As a mother, I was very worried about my daughter Sowjanya’s teeth. She had a severe open bite, and it affected her chewing and speech. I thought only surgery could fix it.\\r\\n\\r\\nBut when we consulted Mydent Aligners, the doctors assured us that it could be corrected with their advanced treatment. They explained every step, and we felt confident moving forward.\\r\\n\\r\\nOver time, we started seeing visible changes. Her bite improved, her smile became more natural, and most importantly, her confidence grew.\\r\\n\\r\\nI’m truly thankful to the Mydent team for treating my daughter with such care and expertise. They made what felt impossible, possible – without any surgery or pain.”\\r\\n\\r\\n— Sowjanya’s Mother', '2025-07-08 10:09:50', '2025-08-01 09:14:37') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (17, 'sumanth story', 'assets/image/infycare-logo.png', 'crowding', 'Simple', '6months', 20, '“I had mild crowding in my front teeth that always bothered me when I smiled. It wasn’t a big issue, but I still wanted to fix it.\\r\\n\\r\\nI chose Mydent Aligners because I wanted a clear and comfortable option. The process was super smooth – no pain, no hassle.\\r\\n\\r\\nWithin a few months, I could see a big difference. My teeth look aligned, and my smile feels more confident now.\\r\\n\\r\\nFor anyone with a simple case like mine, I’d definitely recommend Mydent. It’s easy, effective, and worth it.”\\r\\n\\r\\n— Sumanth, ill give 5starts out of 5', '2025-07-08 10:12:30', '2025-08-01 09:32:09') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (18, 'Prasad story', 'assets/image/infycare-logo.png', 'open bite', 'Moderate', '12', 46, '“I always knew something was off with my bite, even as a kid. I couldn’t close my mouth fully, and my front teeth never touched. Eating certain foods was difficult, and over time, it started affecting how I spoke too.”\\r\\n\\r\\nMy name is Prasad, and I lived with a moderate open bite for years. People would say it’s not noticeable, but for me, it was always there — in every photo, in every meal, and in every moment I hesitated to smile.\\r\\n\\r\\nI had consulted a few dentists in the past, and most of them suggested traditional braces. Some even mentioned surgery down the line. I wasn’t ready for that. I wanted something simpler, less painful, and more suited to my lifestyle.\\r\\n\\r\\nThat’s when I found Mydent Aligners. From the first consultation, I felt hopeful. The team was professional, patient, and took the time to explain everything about open bite correction using aligners. I was amazed that even my moderate case could be handled without braces or surgery.\\r\\n\\r\\nThe treatment was planned in detail. Each aligner was designed to gradually shift my teeth, and with every new set, I could feel the progress. The best part? It was invisible. I continued working, attending events, and living my life without anyone noticing I was undergoing treatment.\\r\\n\\r\\nOver the months, my bite started to close. I could finally bite into foods I used to avoid. My speech improved naturally, and so did my self-esteem.\\r\\n\\r\\nToday, my teeth look aligned, my bite is functional, and I smile without thinking twice.\\r\\n\\r\\nMydent Aligners changed not just my teeth, but how I carry myself in life. I’ll always be grateful for that.”\\r\\n\\r\\n— Prasad M., Mydent Patient', '2025-07-08 10:14:33', '2025-08-01 09:14:26') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (19, 'suhas story', 'assets/image/infycare-logo.png', 'spacing', 'Moderate', '11', 36, '“I had visible gaps between my teeth that always made me feel self-conscious. Even though it wasn’t a severe problem, I used to avoid smiling in pictures or speaking freely in groups.\\r\\n\\r\\nAfter hearing about Mydent Aligners, I decided to give it a try. From the very first scan, the process was smooth and professional. The treatment plan was explained clearly, and I felt confident moving forward.\\r\\n\\r\\nI was given a series of aligners to gradually close the gaps, and within a few months, I could already see the difference. The aligners were easy to wear, comfortable, and barely noticeable.\\r\\n\\r\\nNow, my smile looks balanced and clean – and the confidence it’s given me is priceless. I’m really happy I chose Mydent for my smile journey.”\\r\\n\\r\\n— Suhas', '2025-07-08 10:16:07', '2025-08-01 09:14:14') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (20, 'pavan story', 'assets/image/infycare-logo.png', 'spacing', 'Moderate', '14', 40, '“I had a moderate alignment issue that always made me feel uncomfortable about my smile. It wasn’t extreme, but noticeable enough that it bothered me.\\r\\n\\r\\nI didn’t want traditional braces because of how they look and feel. That’s when I found out about Mydent Aligners, and it turned out to be the perfect solution.\\r\\n\\r\\nThe team did a free scan and gave me a clear plan. The aligners fit well, were easy to manage, and the entire treatment was so smooth.\\r\\n\\r\\nOver the next few months, I started noticing steady changes. My teeth began to align properly, and I didn’t face any pain or speech issues.\\r\\n\\r\\nNow, my smile is more natural and confident. I’m glad I trusted Mydent – they made the whole experience simple and stress-free.”\\r\\n\\r\\n— Pavan, Mydent Patient', '2025-07-08 10:17:36', '2025-08-01 09:14:02') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (21, 'Anandu story', 'assets/image/infycare-logo.png', 'spacing', 'Simple', '8', 24, 'The gaps between my teeth were something I wanted to fix quickly and comfortably, so I chose aligners. The treatment took about 8 months, and the process was straightforward. My dentist was always supportive and clear with explanations. I’m really happy with how my teeth look now.\\r\\n— Anandu', '2025-07-08 10:19:36', '2025-08-01 09:13:50') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (22, 'Bhargavi story', 'assets/image/infycare-logo.png', 'missing', 'Severe', '18', 48, 'I had several missing teeth and was always self-conscious about my smile. After consulting with my dentist, I decided to go ahead with aligner treatment. It took around 18 months, and I couldn’t be happier with the results. The process was smooth, comfortable, and barely noticeable to others. My confidence has improved so much, and I finally feel proud to smile again. Thank you for the incredible care and support throughout my journey!"\\r\\n— Bhargavi', '2025-07-08 10:21:20', '2025-08-01 09:13:11') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (23, 'Manvitha story', 'assets/image/infycare-logo.png', 'crowding', 'Severe', '16', 48, '“I had severe crowding in my teeth for as long as I can remember. My front teeth overlapped badly, and my smile always made me feel insecure.\\r\\n\\r\\nI used to cover my mouth while talking or smiling in public. I was afraid that braces would be painful and too visible, especially as an adult. That’s when I came across Mydent Aligners.\\r\\n\\r\\nThe team was so reassuring during my first consultation. They explained that even severe cases like mine could be treated effectively with aligners – and that gave me hope.\\r\\n\\r\\nThe treatment was detailed and well-monitored. I received a series of aligners and, step by step, my teeth started shifting into proper alignment. It wasn’t always easy, but it was completely worth it.\\r\\n\\r\\nToday, I look at my smile and feel proud. My teeth are straight, my confidence is back, and all of this happened without metal braces or surgery.\\r\\n\\r\\nThank you, Mydent, for transforming my smile and making me believe it was possible.”\\r\\n\\r\\n— Manvitha', '2025-07-08 10:25:40', '2025-08-01 09:12:52') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (24, 'Ganesh story', 'assets/image/infycare-logo.png', 'spacing', 'Severe', '18 months', 48, '"For a long time, I was bothered by the gaps between my teeth. When I chose to get aligners, I wasn’t sure what to expect, but it turned out to be way easier than I imagined. The aligners felt really comfortable, and I barely noticed them while wearing. My dentist was great — always ready to answer my questions and keep me on track. Now, my teeth look awesome and those gaps are completely gone. I’m super happy with the whole experience!"\\r\\n— Ganesh', '2025-07-08 10:26:53', '2025-08-01 09:15:58') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (25, 'Rajitha story', 'assets/image/infycare-logo.png', 'spacing', 'Simple', '4months', 20, '"I underwent aligner therapy to correct the spacing between my teeth. The treatment was efficient and comfortable, and my dentist provided clear guidance and excellent care throughout. I’m very pleased with the results and feel more confident with my smile now."\\r\\n— Rajitha', '2025-07-08 10:28:24', '2025-08-01 09:12:42') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (26, 'Reddy story', 'assets/image/infycare-logo.png', 'spacing', 'Moderate', '8 months', 30, '"I had gaps between my teeth that always made me hesitant to smile. Choosing aligners was a game-changer, and I couldn’t believe how effective and easy the treatment was. My dentist was incredibly supportive from the beginning — always available to answer questions, monitor my progress, and adjust the plan when needed. The care I received felt very personalized, and I always felt like I was in safe hands. Now, my smile looks perfect and natural. I couldn’t be more satisfied with the results and the care I received."\\r\\n— Reddy', '2025-07-08 10:29:53', '2025-08-01 09:12:27') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (27, 'Veerababu story', 'assets/image/infycare-logo.png', 'Forwardly placed', 'Moderate', '12 months', 36, '"My front teeth used to stick out, and it always made me feel awkward, especially when I smiled or talked. I was really conscious of how they looked, and it even affected my confidence. I avoided smiling in pictures and often felt uncomfortable around people.\\r\\n\\r\\nThen I found out about MyDent Aligners. My dentist told me they could help fix the position of my teeth without the need for metal braces. I decided to go for it, and honestly, it was one of the best decisions I’ve made.\\r\\n\\r\\nThe aligners were clear, easy to wear, and no one even noticed I had them on. Over time, I could actually see my teeth moving into the right place. There was no pain, just a bit of pressure at the beginning — but totally manageable.\\r\\n\\r\\nNow my teeth look straight and natural, and my smile has completely changed. I feel so much more confident in myself. I’m really happy with the results, and I’d definitely recommend mydent Aligners* to anyone who wants to fix their teeth without the hassle of traditional braces."', '2025-07-08 10:31:21', '2025-08-01 09:12:11') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `blogs` (`id`, `title`, `thumbnail`, `issue_type`, `issue_level`, `treatment_time`, `aligner_count`, `content`, `created_at`, `updated_at`) VALUES (28, 'Nikhil story', 'assets/image/infycare-logo.png', 'spacing', 'Simple', '4 months', 10, '"I had small gaps between my front teeth that not only made me feel self-conscious but also caused food to get stuck every time I ate. It was frustrating and sometimes even embarrassing. I felt like I had to brush my teeth constantly just to keep them clean. It also made me hesitate to smile in photos or when meeting new people.\\r\\n\\r\\nWhen I finally talked to my dentist about it, they explained the reasons behind the spacing and introduced me to MyDent Aligners as a simple and effective solution to close the gaps. I was a bit nervous at first, but they explained everything clearly, and the whole process was much easier than I expected. The aligners were comfortable, barely noticeable, and didn’t interfere with my daily routine.\\r\\n\\r\\nNow that the treatment is complete, my smile looks more even, and my bite feels more natural. Eating is no longer a hassle, and I don’t worry about food getting stuck anymore. The best part is that I can smile freely and confidently without feeling awkward. Looking back, I honestly wish I had started mydent Aligners sooner. The results were better than I expected, and I’m so glad I chose this treatment."', '2025-07-08 10:32:37', '2025-08-01 09:11:51') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `articles` (1 rows)
INSERT INTO `articles` (`id`, `title`, `content`, `thumbnail`, `created_at`, `updated_at`) VALUES (1, 'Top 5 Oral Hygiene Practices for Aligner Wearers', 'Maintaining optimal oral hygiene while undergoing clear aligner treatment is key to achieving a healthy, bright smile. Always brush after meals and clean your aligner trays daily with mild soap and water.', 'assets/image/infycare-logo.png', '2026-08-17 19:21:16', '2026-08-17 19:21:16') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `homepage_videos` (13 rows)
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (18, 'test 2', 'section-2', 'https://mydent.in/uploads/public/vids/fEYUOLtGWNwwoJkYYjynto3QCt9lG4O33O3sL3DM.mp4', NULL, 1, '2025-07-05 07:17:58', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (25, 'test 1', 'section-2', 'https://mydent.in/uploads/public/vids/9R4awOo83cWuwJJtNTko6s2xCntRWd4Lo79b9LEh.mp4', NULL, NULL, '2025-07-08 10:51:48', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (35, 'Scanning', 'section-1', 'https://mydent.in/uploads/public/vids/ycq7F6gddWlRcq7WGwgLbN9LFwM2NkprKDI8BYtO.mp4', NULL, NULL, '2025-07-08 14:13:18', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (36, 'Delivery of Aligners', 'section-1', 'https://mydent.in/uploads/public/vids/SlluzTPCuh7DMqMufOFB9m56jApwUfJKiXTB70wL.mp4', NULL, NULL, '2025-07-08 14:14:05', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (37, 'Monitoring', 'section-1', 'https://mydent.in/uploads/public/vids/wwjK5i0NHGDiSdQ1BptqfdZHQLqHErWwYcoQvQ4U.mp4', NULL, NULL, '2025-07-08 14:15:21', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (42, 'Customized', 'characteristics', NULL, 'https://mydent.in/uploads/public/images/rvJdyvJgDHZCJtAdkDsOY61q4nf62CdmUVAMGXv8.png', NULL, '2025-07-08 18:40:53', 'storage/imgs/logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (43, 'Invisible', 'characteristics', NULL, 'https://mydent.in/uploads/public/images/bEVrKJNa4CkWgT18ZmogbJIzb47DgK7aow87FS2o.png', NULL, '2025-07-08 18:41:29', 'storage/imgs/logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (44, 'Comfort', 'characteristics', NULL, 'https://mydent.in/uploads/public/images/qqqeRY165k4o3IF59nFDzXDGoVjqjJVzKdNn15Ue.png', NULL, '2025-07-08 18:42:17', 'storage/imgs/logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (45, 'Supervision', 'characteristics', NULL, 'https://mydent.in/uploads/public/images/gIV95kFen84ZYoUb5rbHtCLBx1u0QnVQJv1pxcgp.png', NULL, '2025-07-08 18:43:10', 'storage/imgs/logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (46, 'Progress', 'characteristics', NULL, 'https://mydent.in/uploads/public/images/hU0okfJQffeZohBjGcViEyfXRPPFNburP8r3BxkO.png', NULL, '2025-07-08 18:44:08', 'storage/imgs/logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (50, 'mydent', 'section-3', 'https://mydent.in/uploads/public/vids/mPdkMtkYai1AsStZYLNUuHhvbdpngLutsgAks7h3.mp4', NULL, NULL, '2025-07-09 10:28:49', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (51, 'test x', 'section-4', 'https://mydent.in/uploads/public/vids/ej05C8ZWZTCVOHRlxT72JZrb8pVSdfwxCmWRnL13.mp4', NULL, NULL, '2025-07-13 18:10:23', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `homepage_videos` (`id`, `title`, `section`, `video_path`, `order`, `created_at`, `updated_at`, `image_path`) VALUES (54, 'Listin what our patients say', 'section-5', 'https://mydent.in/uploads/public/vids/OLePAn4o8bmm9Gt5t7OM9hdoOToLdwPZvjHUkMVI.mp4', NULL, NULL, '2025-07-16 19:50:19', 'assets/image/infycare-logo.png') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `main_banners` (5 rows)
INSERT INTO `main_banners` (`id`, `page`, `title`, `image`, `created_at`, `updated_at`) VALUES (13, 'alligners', NULL, 'uploads/vids/686e290a9a146.jpg', '2025-07-09 08:32:10', '2025-07-09 08:32:10') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `main_banners` (`id`, `page`, `title`, `image`, `created_at`, `updated_at`) VALUES (15, 'products', NULL, 'uploads/vids/686e2da6df89b.jpg', '2025-07-09 08:51:50', '2025-07-09 08:51:50') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `main_banners` (`id`, `page`, `title`, `image`, `created_at`, `updated_at`) VALUES (18, 'smileverse', NULL, 'uploads/vids/686e34f366481.jpg', '2025-07-09 09:22:59', '2025-07-09 09:22:59') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `main_banners` (`id`, `page`, `title`, `image`, `created_at`, `updated_at`) VALUES (22, 'centre', NULL, 'uploads/vids/686e3dd6b1c42.jpg', '2025-07-09 10:00:54', '2025-07-09 10:00:54') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `main_banners` (`id`, `page`, `title`, `image`, `created_at`, `updated_at`) VALUES (23, 'why-mydent', NULL, 'uploads/vids/686e419228388.jpg', '2025-07-09 10:16:50', '2025-07-09 10:16:50') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `front_patient_testimonials` (2 rows)
INSERT INTO `front_patient_testimonials` (`id`, `name`, `designation`, `short_description`, `is_default`, `created_at`, `updated_at`) VALUES (1, 'JOHN DOE', 'XYZ Inc.', 'Incidunt deleniti blanditiis quas aperiam recusandae consequatur ullam quibusdam cum libero illo rerum repellendus!', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `front_patient_testimonials` (`id`, `name`, `designation`, `short_description`, `is_default`, `created_at`, `updated_at`) VALUES (2, 'COLLIS TA''EED', 'Envato Inc.', 'Natus voluptatum enim quod necessitatibus quis expedita harum provident eos obcaecati id culpa corporis molestias.', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `faqs` (6 rows)
INSERT INTO `faqs` (`id`, `question`, `answer`, `is_default`, `created_at`, `updated_at`) VALUES (1, 'Doctor Can Ease Your Pain?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, dolorum, vero ipsum molestiae minima odio quo voluptate illum excepturi quam cum voluptates doloribus quae nisi tempore necessitatibus dolores ducimus enim libero eaque explicabo suscipit animi at quaerat aliquid ex expedita perspiciatis? Saepe, aperiam, nam unde quas beatae vero vitae nulla.', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `faqs` (`id`, `question`, `answer`, `is_default`, `created_at`, `updated_at`) VALUES (2, 'How do I withdraw from a subject?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, dolorum, vero ipsum molestiae minima odio quo voluptate illum excepturi quam cum voluptates doloribus quae nisi tempore necessitatibus dolores ducimus enim libero eaque explicabo suscipit animi at quaerat aliquid ex expedita perspiciatis? Saepe, aperiam, nam unde quas beatae vero vitae nulla.', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `faqs` (`id`, `question`, `answer`, `is_default`, `created_at`, `updated_at`) VALUES (3, 'Helpful Resources for Authors', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, dolorum, vero ipsum molestiae minima odio quo voluptate illum excepturi quam cum voluptates doloribus quae nisi tempore necessitatibus dolores ducimus enim libero eaque explicabo suscipit animi at quaerat aliquid ex expedita perspiciatis? Saepe, aperiam, nam unde quas beatae vero vitae nulla.', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `faqs` (`id`, `question`, `answer`, `is_default`, `created_at`, `updated_at`) VALUES (4, 'Can I use trademarked names in my items?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, dolorum, vero ipsum molestiae minima odio quo voluptate illum excepturi quam cum voluptates doloribus quae nisi tempore necessitatibus dolores ducimus enim libero eaque explicabo suscipit animi at quaerat aliquid ex expedita perspiciatis? Saepe, aperiam, nam unde quas beatae vero vitae nulla.', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `faqs` (`id`, `question`, `answer`, `is_default`, `created_at`, `updated_at`) VALUES (5, 'How much money can I make?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, dolorum, vero ipsum molestiae minima odio quo voluptate illum excepturi quam cum voluptates doloribus quae nisi tempore necessitatibus dolores ducimus enim libero eaque explicabo suscipit animi at quaerat aliquid ex expedita perspiciatis? Saepe, aperiam, nam unde quas beatae vero vitae nulla.', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `faqs` (`id`, `question`, `answer`, `is_default`, `created_at`, `updated_at`) VALUES (6, 'How do I pay for items on the Marketplaces?', 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Assumenda, dolorum, vero ipsum molestiae minima odio quo voluptate illum excepturi quam cum voluptates doloribus quae nisi tempore necessitatibus dolores ducimus enim libero eaque explicabo suscipit animi at quaerat aliquid ex expedita perspiciatis? Saepe, aperiam, nam unde quas beatae vero vitae nulla.', 1, '2023-09-28 07:51:56', '2023-09-28 07:51:56') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `settings` (15 rows)
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (1, 'default_country_code', 'in', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (2, 'clinic_name', 'mydent', '2023-09-28 07:51:48', '2025-04-21 01:35:17') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (3, 'contact_no', '9381590963', '2023-09-28 07:51:49', '2025-07-10 20:22:23') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (4, 'email', 'support@mydent.in', '2023-09-28 07:51:49', '2025-07-10 20:24:56') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (5, 'specialities', '["13"]', '2023-09-28 07:51:49', '2025-07-05 08:48:45') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (6, 'currency', '2', '2023-09-28 07:51:49', '2025-04-23 06:48:31') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (7, 'address_one', 'Head office 1: Dhanvantari 2B 80 ft road KHB colony, 2, stage Basaveshwarnagar, Bengaluru, Karnataka 560079', '2023-09-28 07:51:49', '2025-07-12 18:37:47') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (8, 'address_two', 'Head Office 2: H no: 1-1-534, opp Post Office, y junction, Gandhinagar, Hyderabad .', '2023-09-28 07:51:49', '2025-07-12 18:37:47') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (9, 'country_id', '101', '2023-09-28 07:51:49', '2023-09-28 07:51:49') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (10, 'state_id', '36', '2023-09-28 07:51:49', '2025-07-12 18:37:47') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (11, 'city_id', '4460', '2023-09-28 07:51:49', '2025-07-12 18:37:47') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (12, 'postal_code', '500080', '2023-09-28 07:51:49', '2025-07-12 18:37:47') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (13, 'logo', 'storage/imgs/logo.png', '2023-09-28 07:51:49', '2025-07-12 13:01:34') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (14, 'favicon', 'https://mydent.in/uploads/31/Untitled_design__38_-removebg-preview.png', '2023-09-28 07:51:49', '2025-07-12 18:35:12') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `settings` (`id`, `key`, `value`, `created_at`, `updated_at`) VALUES (15, 'region_code', '91', '2023-09-28 07:51:49', '2023-09-28 07:51:49') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `sliders` (1 rows)
INSERT INTO `sliders` (`id`, `title`, `short_description`, `is_default`, `created_at`, `updated_at`) VALUES (1, 'Clear, comfortable Aligners solutions, created by expert orthodontists', 'mydent Clear Aligners Invisible Path to a Smile', 1, '2023-09-28 07:51:56', '2025-07-16 14:13:59') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `doctor_specialization` (5 rows)
INSERT INTO `doctor_specialization` (`id`, `doctor_id`, `specialization_id`, `created_at`, `updated_at`) VALUES (27, 12, 10, NULL, NULL) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctor_specialization` (`id`, `doctor_id`, `specialization_id`, `created_at`, `updated_at`) VALUES (29, 14, 13, NULL, NULL) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctor_specialization` (`id`, `doctor_id`, `specialization_id`, `created_at`, `updated_at`) VALUES (30, 15, 13, NULL, NULL) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctor_specialization` (`id`, `doctor_id`, `specialization_id`, `created_at`, `updated_at`) VALUES (31, 16, 13, NULL, NULL) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `doctor_specialization` (`id`, `doctor_id`, `specialization_id`, `created_at`, `updated_at`) VALUES (33, 11, 13, NULL, NULL) ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `service_doctor` (7 rows)
INSERT INTO `service_doctor` (`id`, `service_id`, `doctor_id`) VALUES (9, 1, 12) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_doctor` (`id`, `service_id`, `doctor_id`) VALUES (10, 2, 14) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_doctor` (`id`, `service_id`, `doctor_id`) VALUES (11, 3, 14) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_doctor` (`id`, `service_id`, `doctor_id`) VALUES (12, 7, 14) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_doctor` (`id`, `service_id`, `doctor_id`) VALUES (13, 4, 14) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_doctor` (`id`, `service_id`, `doctor_id`) VALUES (14, 8, 11) ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `service_doctor` (`id`, `service_id`, `doctor_id`) VALUES (15, 8, 14) ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `session_week_days` (6 rows)
INSERT INTO `session_week_days` (`id`, `doctor_id`, `doctor_session_id`, `day_of_week`, `start_time`, `end_time`, `start_time_type`, `end_time_type`, `created_at`, `updated_at`) VALUES (1, 11, 1, '1', '12:00', '11:45', 'AM', 'PM', '2025-04-28 01:08:44', '2025-04-28 01:08:44') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `session_week_days` (`id`, `doctor_id`, `doctor_session_id`, `day_of_week`, `start_time`, `end_time`, `start_time_type`, `end_time_type`, `created_at`, `updated_at`) VALUES (2, 11, 1, '2', '12:00', '11:45', 'AM', 'PM', '2025-04-28 01:08:44', '2025-04-28 01:08:44') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `session_week_days` (`id`, `doctor_id`, `doctor_session_id`, `day_of_week`, `start_time`, `end_time`, `start_time_type`, `end_time_type`, `created_at`, `updated_at`) VALUES (3, 11, 1, '3', '12:00', '11:45', 'AM', 'PM', '2025-04-28 01:08:44', '2025-04-28 01:08:44') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `session_week_days` (`id`, `doctor_id`, `doctor_session_id`, `day_of_week`, `start_time`, `end_time`, `start_time_type`, `end_time_type`, `created_at`, `updated_at`) VALUES (4, 11, 1, '4', '12:00', '11:45', 'AM', 'PM', '2025-04-28 01:08:44', '2025-04-28 01:08:44') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `session_week_days` (`id`, `doctor_id`, `doctor_session_id`, `day_of_week`, `start_time`, `end_time`, `start_time_type`, `end_time_type`, `created_at`, `updated_at`) VALUES (5, 11, 1, '5', '12:00', '11:45', 'AM', 'PM', '2025-04-28 01:08:44', '2025-04-28 01:08:44') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `session_week_days` (`id`, `doctor_id`, `doctor_session_id`, `day_of_week`, `start_time`, `end_time`, `start_time_type`, `end_time_type`, `created_at`, `updated_at`) VALUES (6, 11, 1, '6', '12:00', '11:45', 'AM', 'PM', '2025-04-28 01:08:44', '2025-04-28 01:08:44') ON DUPLICATE KEY UPDATE `id`=`id`;

-- Data for table `clinic_schedules` (8 rows)
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (1, '1', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (2, '2', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (3, '3', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (4, '4', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (5, '5', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (6, '6', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (7, '7', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;
INSERT INTO `clinic_schedules` (`id`, `day_of_week`, `start_time`, `end_time`, `created_at`, `updated_at`) VALUES (8, '0', '12:00 AM', '11:45 PM', '2023-09-28 07:51:46', '2023-09-28 07:51:46') ON DUPLICATE KEY UPDATE `id`=`id`;

SET FOREIGN_KEY_CHECKS=1;
